
// // struct Position {
// //   mut x : Int
// //   mut y : Int
// // }

// // let pos : Position = { x: 0, y: 0 }

// fn init {
    //  @wasm4.trace("hello world");
//   let array = [1, 2, 3, 4, 5]
//   // array = [4, 5, 6, 7, 8] // 错误：`let` 创建的是不可变绑定。
//   let mut mut_array = [1, 2, 3, 4, 5]
//   mut_array = [4, 5, 6, 7, 8]
//   println(mut_array)
// }


// pub fn update() -> Unit {
//   //  @wasm4.set_draw_colors(2) // 选用调色板索引为2的颜色，即茜红 
//   // @wasm4.rect(0, 0, 80, 80) // 用茜红绘制一个矩阵 四个参数分别为第三象限的 x, y, width, heigh
//   // @wasm4.set_draw_colors(4) 
//   // @wasm4.line(0, 0, 80, 80)   //一条斜线 从左上到中间(叠加到矩形之上)
//   // @wasm4.line(0, 80, 160, 80) // 中间一条横线 (叠加到矩形之上)
//   // @wasm4.line(80, 0, 80, 160) // 中间一条竖	线 (叠加到矩形之上)
//   // @wasm4.set_draw_colors(3) 
//   // @wasm4.oval(80, 80, 80,80 ) // 圆 第四象限

//   //  if pos.x + 80 <= 160 {
//   //   pos.x += 1
//   // }
//   //  if pos.y + 80 <= 160 {
//   //   pos.y += 1
//   }

//   //   if @wasm4.get_gamepad(index=1).button_right && pos.x + 80 < 160 {
//   //   pos.x += 1
//   // } else if @wasm4.get_gamepad(index=1).button_down && pos.y + 80 < 160 {
//   //   pos.y += 1
//   // } else if @wasm4.get_gamepad(index=1).button_left && pos.x >= 0 {
//   //   pos.x -= 1
//   // } else if @wasm4.get_gamepad(index=1).button_up && pos.y >= 0 {
//   //   pos.y -= 1
//   // }
  
//    @wasm4.set_draw_colors(index=1, 2)
//   @wasm4.rect(pos.x, pos.y, 80, 80)
// }
// pub fn start() -> Unit {
// @wasm4.trace("hello world");
  // @wasm4.trace("Hello world!");
  // @wasm4.set_palette(1, @wasm4.rgb(0x282e30)) // 暗岩灰
  // @wasm4.set_palette(2, @wasm4.rgb(0xaa337f)) // 陈玫红 Maximum Red Purple
  // @wasm4.set_palette(3, @wasm4.rgb(0xd4392e)) // 茜红
  // @wasm4.set_palette(4, @wasm4.rgb(0x898f92)) //

}

